name: 'Monitor release'

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check-prerelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: 'Monitor release'
        uses: stefanbosak/gh-actions/monitor-release@main
        with:
          project_owner: 'github'
          project_repo: 'copilot-cli'
